### ISSUE TITLE
Maven build error

### ISSUE THREAD

**Issue by jadler1** [SIMULAP/simulap-plugin-sip#4]
## Description

When attempting to build simulap-plugin-sip, there is a build error after calling `> mvn -X clean package `. 
The error message reads: 
`Failed to execute goal on project simulap-plugin-sip: Could not resolve dependencies for project com.hpe.simulap:simulap-plugin-sip:pom:1.8.0-0.0: The following artifacts could not be resolved: javax.sip:jain-sip-api:jar:1.2.0-3, javax.sip:jain-sip-ri:jar:1.2.234.2-hpe-1: Could not find artifact javax.sip:jain-sip-api:jar:1.2.0-3 in central (https://repo.maven.apache.org/maven2)`

## Motivation and Context

* Project context: 
* SIMULAP version: 1.0
* Operating System version: Windows 10 enterprise

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I give my issue a label.
- [ ] I put my issue into `Support` project.
- [ ] I provide the required resources.

**Comment by regnauch** [comment]
fixed
